apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  N8N_ENCRYPTION_KEY: {{ .Values.secret.N8N_ENCRYPTION_KEY | quote }}
  DB_POSTGRESDB_PASSWORD: {{ .Values.secret.DB_POSTGRESDB_PASSWORD | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.POSTGRES_PASSWORD | quote }}
  N8N_RUNNERS_AUTH_TOKEN: {{ .Values.secret.N8N_RUNNERS_AUTH_TOKEN | quote }}
