apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-pvc
  namespace: {{ .Release.Namespace }}

spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 2Gi